---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-ms
          image: pabalaba/customer:latest
          ports:
          - containerPort: 5000
          volumeMounts:
          - mountPath: /app/config
            readOnly: true
            name: customer-conf
      volumes:
      - name: customer-conf
        configMap:
          name: customer-conf
          items:
            - key: appsettings.json
              path: appsettings.json
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32105
      port: 5000
      targetPort: 5000
  selector:
    app: customer
---
apiVersion: v1
kind: ConfigMap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "CustomerConnection": "Server=customers-mysql;Port=3306;Database=customerdb;Uid=pabalaba;Pwd=pabalaba;"
      }
    }
metadata:
  name: customer-conf
  namespace: default