name: Build microservice

on:
  workflow_dispatch:

jobs:
  build-books:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BookMicroservice/
    steps:
    - uses: actions/checkout@v2
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 books-mysql" | sudo tee -a /etc/hosts
    - name: Get branch
      id: get_branch
      run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Get the commit SHA
      id: get_commit_sha
      run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        path: BookMicroservice/
        dockerfile: BookMicroservice/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/book
        tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}, latest
        build_args: |
          TAG=${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}